### ISSUE TITLE
Published to npm?

### ISSUE THREAD

**Issue by pke** [jh3y/driveway#11]
Seems like this package has not been published in npm yet?

**Comment by alexcastillo** [comment]
+1

**Comment by jh3y** [comment]
True! Happy to publish if that's useful for people.

I'm also going to add an optional JavaScript helper for chronological ordering in a revised version soon hopefully.

I've implemented it already [here](http://codepen.io/jh3y/details/vgZWZL)

@jh3y

**Comment by jh3y** [comment]
Current state of `master@v1.0.0` published on `npm` [here](https://www.npmjs.com/package/driveway) :smile:

I'm fully expecting a new issue now to add `npm` badge and installation to the `README` :joy:

Spotted a few things I'd like to change so expect some new versions on the way! 🚀 

@jh3y

**Comment by alexcastillo** [comment]
@jh3y Thank you so much for your contributions and getting this done so quickly!

**Comment by pke** [comment]
Its very useful already, @jh3y thanks a lot! I have created a bunch of reactjs components using ur CSS. Looks really smooth. Maybe it would make sense to convert it to styled-components but I am not sure.

**Comment by jh3y** [comment]
Thanks for the kind words @alexcastillo 😄 

And the same to you @pke 😄 

Sounds good. I do like `styled-components`. That could be a great fit if using within `react`. I think there are potentially some packages out there that you could use with `webpack` in order to get access to a stylesheet file as an `Object` exposing the styles/rules etc.

This could enable potentially something like;

```
import { dw-cluster } from 'driveway.css'
import styled from 'styled-components'

const Cluster = styled.div`
  ${dw-cluster}
`
```

@jh3y
