### ISSUE TITLE
Whats the deal with the class names?

### ISSUE THREAD

**Issue by jonagoldman** [jh3y/driveway#5]
Hey, sorry for not following your issue guidelines, but I just want to know whats the deal with the class names. Its extremely hard to understand all the abbreviations, just look at this:

``` html
<div class="dw-pnl dw-flp dw-flp--md">
  <div class="dw-pnl__cntnt dw-flp__cntnt">
    <div class="dw-flp__pnl dw-flp__pnl--frnt">
      <h1>You can flip me round</h1>
    </div>
    <div class="dw-flp__pnl dw-flp__pnl--bck">
      <h1>Yeah that's right</h1>
    </div>
  </div>
</div>
```

What?! Is this supposed to be more readable?

What about this alternative:

``` html
<div class="dw-panel dw-flip dw-flip-medium">
  <div class="dw-panel-content dw-flip-content">
    <div class="dw-flip-panel dw-flip-panel-front">
      <h1>You can flip me round</h1>
    </div>
    <div class="dw-flip-panel dw-flip-panel-back">
      <h1>Yeah that's right</h1>
    </div>
  </div>
</div>
```

**Comment by alizain** [comment]
Honestly, removing vowels for does not remove "class bloat". It makes for a poor UX with difficult-to-understand names that require unnecessary mental processing to decipher.

IMHO: **mental efficiency** > character efficiency, byte efficiency, everything else

**Comment by jh3y** [comment]
Understand that you may not "like" the classnames but for me personally, this is a non issue. I may consider changing it when I have some time for it.

However, to use labels such as "poor UX" is unnecessary and unwarranted. It's opinionated and that's _your_ opinion. The `README` clearly states that __you__ can roll your own class names.

**Comment by alizain** [comment]
Yes, it makes sense that this is not an issue for you because you wrote the library. Naturally, one would assume that the meaning the "sgmnt" is instantly clear to you.

However, when someone **new** tries to grok your work, the shortening of words makes the task **unnecessarily more difficult**.

As I reasoned in my earlier comment, the justification for this in your blog post was "reducing bloat". Your readme has to spell out the meaning of each classname for greater clarity. Perhaps that is a clear indication of the decreased mental efficiency due to bloat reduction.

And finally, about the "label" I used. I find it very troublesome that you're immediately reaching for this escape hatch when presented with an opinion that you probably don't like. Let me be clear, "poor UX" is not a label. It's an adjective (poor) that I'm using to describe a property of your library (UX).

To say that I'm using an "unnecessary and unwarranted label" is... Let's use an example. Alice says, "the weather is disgusting today". Does it make sense for Bob to say, "don't label the weather as 'disgusting'"? In my opinion, it doesn't. If "poor UX" is a label, than all adjectives are essentially labels. I hope we haven't become that brittle as a society.

And finally, to reiterate: I am a user of your library. My experience using it was poor because I was not instantly familiar with the remove-all-vowels-to-abbreviate classnames, and quite possibly a healthy dose of my own stupidity. Hence, the library's UX was poor for me. 

Disclaimer: all of this is simply thoughts/opinions/advice from a programmer to another programmer. I did change your classnames, simplify them to exactly what I needed, and use them. Great work btw, saved me a ton of time!
